### ISSUE TITLE
Output also a source map

### ISSUE THREAD

**Issue by Ciantic** [jgreene/watch-less#10]
I'd like to output source map file also. Preferably so that if I use switch `-e .css` then the map file is automatically `.css.map`.

**Comment by jgreene** [comment]
This shouldn't be difficult to implement and I would happily accept a pull request.  http://lesscss.org/usage/ mentions the apis that would need be used.

**Comment by bammoo** [comment]
Is there anyone would like to do this?

**Comment by Ciantic** [comment]
I'm btw using this myself these days:

watch-run -p "**/*.less" "lessc --verbose --source-map --glob style.less style.css"

On windows. It works well enough for me. See [watch-run](https://github.com/queckezz/watch-run)
